# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-bionic
strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda create -f environment.yml
  displayName: Create Anaconda environment
      
- bash: |
    source activate blocksim
  displayName: Activate Anaconda environment
      
- bash: |
    tox -e py
    codecov
    coverage html
  displayName: Tests
