name: blocksim
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=4.2
  - cartopy=0.18.0
  - control=0.8.4
  - ipython=7.21.0
  - jplephem=2.15
  - matplotlib=3.3.4
  - numpy=1.20.1
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.7.10
  - pyyaml=5.4.1
  - scipy=1.6.1
  - setuptools=49.6.0
  - sgp4=2.18
  - skyfield=1.37
  - slycot=0.4.0.0
  - tqdm=4.59.0
  - wheel=0.36.2
  - pip:
    - codecov==2.1.11
    - coverage==5.5
    - docutils==0.16
    - dummyserial==1.0.0
    - pre-commit==2.11.1
    - pyserial==3.5
    - pytest==6.2.2
    - pytest-cov==2.11.1
    - pytest-mpl==0.12
    - tox==3.23.0
    - tox-conda==0.7.1
    - twine==3.4.1
    - virtualenv==20.4.3
    