# environment.yml
name: bs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - control=0.9.0
  - matplotlib=3.3.4
  - numpy=1.19.5
  - panda3d=1.10.10
  - parse=1.19.0
  - pip=21.3.1
  - python=3.6.13
  - pyyaml=5.4.1
  - scipy=1.5.3
  - slycot=0.4.0.0
  - tqdm=4.62.3
  - wheel=0.37.0
  