name: bs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - alsa-lib=1.2.3
  - aom=3.2.0
  - assimp=5.0.1
  - astroid=2.8.0
  - attrs=21.2.0
  - babel=2.9.1
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bullet=2.89
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - codecov=2.1.11
  - colorama=0.4.4
  - control=0.9.0
  - coverage=6.0
  - cryptography=35.0.0
  - cycler=0.10.0
  - dbus=1.13.6
  - docutils=0.17.1
  - expat=2.4.1
  - ffmpeg=4.4.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.70.0
  - glib-tools=2.70.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=68.1
  - idna=3.1
  - ilmbase=2.5.5
  - imagecodecs-lite=2019.12.3
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - iniconfig=1.1.1
  - jbig=2.1
  - jinja2=3.0.2
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.8
  - libdrm=2.4.107
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.70.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopenblas=0.3.12
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=13.3
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libva=2.13.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mesalib=18.3.1
  - mock=4.0.3
  - more-itertools=8.10.0
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - ncurses=6.2
  - nettle=3.6
  - nspr=4.30
  - nss=3.69
  - numpy=1.19.5
  - olefile=0.46
  - openal-soft=1.20.1
  - openexr=2.5.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - panda3d=1.10.10
  - parse=1.19.0
  - pbr=5.6.0
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3.1
  - pluggy=1.0.0
  - pockets=0.9.1
  - pthread-stubs=0.4
  - py=1.10.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.3
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - pytest-mpl=0.13
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2021.3
  - pyyaml=5.4.1
  - qt=5.12.9
  - readline=8.1
  - requests=2.26.0
  - scipy=1.5.3
  - setuptools=58.0.4
  - six=1.16.0
  - slycot=0.4.0.0
  - snowballstemmer=2.1.0
  - sphinx=4.2.0
  - sphinx-autoapi=1.8.4
  - sphinx-gallery=0.10.0
  - sphinx_rtd_theme=1.0.0
  - sphinxcontrib-apidoc=0.3.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-dotnetdomain=0.4
  - sphinxcontrib-golangdomain=0.2.0.dev0
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - tifffile=2020.6.3
  - tk=8.6.11
  - toml=0.10.2
  - tomli=1.2.2
  - tornado=6.1
  - tqdm=4.62.3
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - unidecode=1.3.2
  - urllib3=1.26.7
  - wheel=0.37.0
  - wrapt=1.12.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
prefix: /home/ydethe/.conda/envs/bs_env
