name: sim
channels:
  - conda-forge
  - defaults
dependencies:
  - adwaita-icon-theme=40.1.1=hca03da5_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py38hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h1a28f6b_0
  - astroid=2.9.0=py38hca03da5_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atk-1.0=2.36.0=h7fe96df_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - black=22.3.0=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.4=py38heec5a64_0
  - brotli=1.0.7=hc377ac9_0
  - brotlipy=0.7.0=py38h1a28f6b_1002
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h1a28f6b_0
  - ca-certificates=2022.3.29=hca03da5_0
  - cairo=1.16.0=h0ab239c_1
  - cartopy=0.18.0=py38h56a4025_2
  - certifi=2021.10.8=py38h10201cd_2
  - cffi=1.15.0=py38h22df2f2_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38hca03da5_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - control=0.9.1=pyhd8ed1ab_2
  - coverage=6.3.2=py38h1a28f6b_0
  - cryptography=36.0.0=py38h834c97f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=h8280c03_0
  - debugpy=1.5.1=py38hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docutils=0.18.1=py38hca03da5_2
  - entrypoints=0.3=py38hca03da5_0
  - epoxy=1.5.4=h1a28f6b_2
  - et_xmlfile=1.0.1=py_1001
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=hc377ac9_0
  - fontconfig=2.13.1=h1f4a5ec_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h1192e45_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.6=h74ef11a_4
  - geos=3.9.1=hc377ac9_1
  - gettext=0.21.0=h826f4ad_0
  - giflib=5.2.1=h1a28f6b_0
  - glib=2.69.1=h98b2900_1
  - gobject-introspection=1.68.0=py38h3459c9f_3
  - graphite2=1.3.14=h0e5e14a_0
  - greenlet=1.1.0=py38hc377ac9_0
  - gtk3=3.24.21=h321fa23_1
  - harfbuzz=2.8.1=hffeda63_0
  - hicolor-icon-theme=0.17=hca03da5_2
  - icu=68.1=hc377ac9_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py38hca03da5_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.6.0=pyhd8ed1ab_1
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.9.1=py38hca03da5_0
  - ipython=8.2.0=py38hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py38hca03da5_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9d=h1a28f6b_0
  - jsonschema=3.2.0=py38hca03da5_0
  - jupyter=1.0.0=py38hca03da5_7
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py38hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.2=py38hc377ac9_0
  - krb5=1.19.2=h3b8d789_0
  - lazy-object-proxy=1.6.0=py38h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - libblas=3.9.0=13_osxarm64_openblas
  - libcblas=3.9.0=13_osxarm64_openblas
  - libcurl=7.82.0=hc6d1d07_0
  - libcxx=13.0.1=h6a5c8ee_0
  - libedit=3.1.20210910=h1a28f6b_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=hf27765b_0
  - libffi=3.4.2=hc377ac9_2
  - libgfortran=5.0.0=11_1_0_h6a59814_26
  - libgfortran5=11.1.0=h6a59814_26
  - libiconv=1.16=h1a28f6b_1
  - liblapack=3.9.0=13_osxarm64_openblas
  - libnghttp2=1.46.0=h95c9599_0
  - libopenblas=0.3.18=hea475bc_0
  - libpng=1.6.37=hb8d0fd4_0
  - libpq=12.9=h65cfe13_1
  - librsvg=2.50.7=h90a7944_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.9.0=hf27765b_1
  - libtiff=4.2.0=h11e2f9f_0
  - libwebp=1.2.2=h68602c7_0
  - libwebp-base=1.2.2=h1a28f6b_0
  - libxml2=2.9.12=h8c5e841_0
  - libxslt=1.1.34=h9833966_0
  - libzlib=1.2.11=h90dfc92_1014
  - llvm-openmp=12.0.0=haf9daa7_1
  - lz4-c=1.9.3=hc377ac9_0
  - mako=1.1.4=pyhd3eb1b0_0
  - markdown=3.3.4=py38hca03da5_0
  - markupsafe=2.0.1=py38h1a28f6b_0
  - matplotlib=3.5.1=py38hca03da5_1
  - matplotlib-base=3.5.1=py38hc377ac9_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py38h1a28f6b_1000
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py38hca03da5_1
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.4.4=py38hca03da5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h1a28f6b_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.7.1=pyhd3eb1b0_0
  - ninja=1.10.2=py38h525c30c_3
  - notebook=6.4.8=py38hca03da5_0
  - nspr=4.33=hc377ac9_0
  - nss=3.74=h142855e_0
  - numexpr=2.8.1=py38h144ceef_0
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1n=h90dfc92_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.48.7=h79d33a7_0
  - parse=1.19.0=pyh44b312d_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=hc377ac9_0
  - pdoc3=0.9.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py38h4d1bdd5_0
  - pip=21.2.4=py38hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=2.4.0=pyhd3eb1b0_0
  - pluggy=1.0.0=py38hca03da5_1
  - proj=7.2.0=heac154c_1
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psycopg2=2.8.6=py38hf27765b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyh6c4a22f_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.12.2=py38hca03da5_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.15.2=py38he8f2410_0
  - pyrsistent=0.18.0=py38h1a28f6b_0
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py38hca03da5_0
  - pytest=7.1.1=py38hca03da5_0
  - pytest-cov=3.0.0=pyhd8ed1ab_0
  - pytest-mpl=0.14.0=pyhd8ed1ab_0
  - python=3.8.13=h7e095e3_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2022.1=pyhd8ed1ab_0
  - pyzmq=22.3.0=py38hc377ac9_2
  - qt=5.15.2=h4e944ae_2
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=h1a28f6b_1
  - regex=2022.3.15=py38h1a28f6b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - shapely=1.7.1=py38h18ef730_5
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyhd3eb1b0_1
  - slycot=0.4.0.0=py38he72a9d7_8
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.2=h1058600_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py38hca03da5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.12=he1e0b03_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.1=py38h1a28f6b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py38h1a28f6b_1
  - typer=0.4.1=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38hca03da5_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38hca03da5_0
  - wrapt=1.13.3=py38h1a28f6b_2
  - xz=5.2.5=h1a28f6b_0
  - zeromq=4.3.4=hc377ac9_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h90dfc92_1014
  - zstd=1.4.9=h8574219_1
  - pip:
    - execnet==1.9.0
    - jplephem==2.17
    - lazy-property==0.0.1
    - mpmath==1.2.1
    - numpy==1.22.3
    - panda3d==1.10.11.post1
    - pandas==1.4.2
    - psycopg2-binary==2.9.3
    - pyqt5-sip==4.19.25
    - pyqtchart==5.15.2
    - pytest-forked==1.4.0
    - pytest-xdist==2.5.0
    - scikit-commpy==0.6.0
    - scipy==1.8.0
    - setuptools==61.3.1
    - sgp4==2.20
    - singleton3==1.0
    - skyfield==1.39
    - sqlalchemy==1.3.24
    - sympy==1.10.1
    - tokenize-rt==4.2.1
    - tqdm==4.64.0
    