name: sim
channels:
  - conda-forge
  - defaults
dependencies:
  - black=22.3.0
  - cartopy=0.18.0
  - control=0.9.1
  - coverage=6.3.2
  - docutils=0.17.1
  - ipython=7.23.1
  - jinja2=3.0.3
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - mistune=0.8.4
  - nbconvert=6.5.0
  - networkx=2.7.1
  - openpyxl=3.0.9
  - parse=1.19.0
  - pdoc3=0.10.0
  - pip=21.2.4=py38hca03da5_0
  - pluggy=1.0.0=py38hca03da5_1
  - psycopg2=2.8.6=py38hf27765b_1
  - pylint=2.13.5=py38hca03da5_1
  - pytest=7.1.1
  - pytest-cov=3.0.0
  - pytest-mpl=0.14.0
  - python=3.8.13
  - slycot=0.4.0.0
  - typer=0.4.1
  - wheel=0.37.1
  - pip:
    - lazy-property==0.0.1
    - numpy==1.22.3
    - panda3d==1.10.11.post1
    - pandas==1.4.2
    - psycopg2-binary==2.9.3
    - pytest-xdist==2.5.0
    - scikit-commpy==0.6.0
    - scipy==1.8.0
    - setuptools==61.3.1
    - sgp4==2.20
    - singleton3==1.0
    - skyfield==1.39
    - sqlalchemy==1.3.24
    - tqdm==4.64.0
