# environment_test.yml
# conda install -y mamba -n base -c conda-forge
# mamba env create -f environment_test.yml
# mamba env export --no-build > environment_test.yml
name: bs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov=2.1.11
  - control=0.9.0
  - docutils=0.17.1
  - matplotlib=3.4.3
  - mock=4.0.3
  - numpy=1.21.3
  - panda3d=1.10.10
  - parse=1.19.0
  - pip=21.3.1
  - typer=0.4.0
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - pytest-mpl=0.13
  - python=3.8.12
  - pyyaml=6.0
  - scipy=1.7.1
  - slycot=0.4.0.0
  - sphinx=3.5.3
  - sphinx-autoapi=1.8.4
  - sphinx-gallery=0.10.0
  - sphinx_rtd_theme=1.0.0
  - sphinxcontrib-apidoc=0.3.0
  - sphinxcontrib-napoleon=0.7
  - tqdm=4.62.3
  - wheel=0.37.0
  - twine=3.4.2
  - cartopy=0.20.1
  - pip:
      - lazy_property==0.0.1
