# conda env update --file docs/environment.yml
name: blocksim
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=4.2
  - cartopy=0.18.0
  - control=0.8.4
  - ipython=7.21.0
  - jplephem=2.15
  - matplotlib=3.3.4
  - numpy=1.20.1
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.7.10
  - pyyaml=5.4.1
  - scipy=1.6.1
  - setuptools=49.6.0
  - sgp4=2.18
  - skyfield=1.37
  - slycot=0.4.0.0
  - tqdm=4.59.0
  - pip:
    - sphinx==3.5.1
    - sphinx_rtd_theme==0.4.3
    - sphinx-autoapi==1.7.0
    - sphinx-gallery==0.8.2
    - sphinxcontrib-apidoc==0.3.0
    - sphinxcontrib-napoleon==0.7
    - mock==4.0.3
