name: blocksim
channels:
  - conda-forge
  - defaults
dependencies:
  - control=0.8.4
  - networkx=2.5
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - numpy=1.19.2
  - pillow=8.1.1
  - pip=21.0.1
  - pyserial=3.4
  - python=3.6.13
  - pyyaml=5.4.1
  - scipy=1.4.1
  - setuptools=52.0.0
  - slycot=0.4.0.0
  - tqdm=4.56.0
  - pip:
    - sphinx==3.5.1
    - sphinx_rtd_theme==0.4.3
    - sphinx-autoapi==1.7.0
    - sphinx-gallery==0.8.2
    - sphinxcontrib-apidoc==0.3.0
    - sphinxcontrib-napoleon==0.7
    - mock==4.0.3
